### PR TITLE
chore: adds motion detection example and updates plotter format

### LINKED ISSUE #12: Example for motion detection interrupt
Hi! Is there any complete example for getting motion detection interrupt using this library? I noticed that someone has already implemented on the pull request but the same guy didn't give us a complete valid example, just a small snippet. I tried to use this snippet but I haven't got success on achieving this detection.

### PR DESCRIPTION
**Pull request by gabrielcsapo**
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

fixes #12 

The changes for the plotter format can be found here https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-serial-plotter which shows that we must now have a label for each plot point.

This change will look the following when run:

Screen Shot 2022-02-24 at 6 52 28 PM

The motion detection example runs as well and I have tested this, let me know if you would like a video or some validation, but the interrupt gets triggered on any initial motion. If there is continued motion it will require the device to stop moving and move it again. More on this can be found here http://www.haoyuelectronics.com/Attachment/GY-521/mpu6050.pdf on page 33 under motion interrupt.

Screen Shot 2022-02-25 at 2 03 38 PM

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

No limitations

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

I have run the examples provided before creating the PR.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by ladyada** [comment]
ok please rebase from master so we can test against CI

**Comment by ladyada** [comment]
hiya! thanks so much for submitting a PR! we can review & merge PRs once they have passed continuous integration (CI). that means that code compiles cleanly for all tested platforms, is clang formatted so we maintain the same text formatting for all new code, and is doxygen documented.
if your code isnt passing, check the CI output (click on the red X next to the PR to scroll through the log and find where the error is

here is a tutorial on doxygen: https://learn.adafruit.com/the-well-automated-arduino-library/doxygen

and clang-format: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

and overall how to contribute PRs to libraries: https://learn.adafruit.com/contribute-to-arduino-with-git-and-github

once you get that green checkmark that indicates CI has passed, please comment reply to this post so we know its time for another review (we may not get notified on CI pass and miss that its time to look!)

**Comment by gabrielcsapo** [comment]
@ladyada PR passes after rebasing.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thanks!

**Pull request merged**
